name: Multi Step Workflow

# Déclenche le workflow à chaque push sur n'importe quelle branche
on:
  push:

jobs:
  demo_steps:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : récupérer le code du repo
      - name: Checkout du code
        uses: actions/checkout@v3

      # Étape 2 : afficher un message
      - name: Message
        run: echo "Hello GitHub Actions"

      # Étape 3 : afficher la date actuelle
      - name: Date
        run: date
# Étape 4 : afficher le nom de la branche
      - name: Branche
        run: echo 'Branche : ${{ github.ref }}'
